# Assignment Day 3

In [1]:
#Question NO. 1

import numpy as np
arr=np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [2]:
#Question NO. 2
import numpy as np
list1=[]
list2=[]
for i in range(5):
    n=int(input())
    list1.append(n)
print("list 1 :",list1)
for i in range(5):
    n=int(input())
    list2.append(n)
print("list 2 :",list2)
arr1=np.array(list1)
arr2=np.array(list2)
concat= np.concatenate((arr1,arr2))
print("concatenated array :",concat)
print("sorted array :",np.sort(concat))

5
2
4
6
2
list 1 : [5, 2, 4, 6, 2]
8
2
5
9
7
list 2 : [8, 2, 5, 9, 7]
concatenated array : [5 2 4 6 2 8 2 5 9 7]
sorted array : [2 2 2 4 5 5 6 7 8 9]


In [3]:
#Question NO. 3

import numpy as np

arr = np.array([[1, 4, 7], [3, 6, 9], [1, 4, 7], [3, 6, 9],[8,5,6]])
print("Dimensions of array :",arr.ndim)

print("Size of array :",arr.size)

Dimensions of array : 2
Size of array : 15


In [4]:
#Question NO. 4

import numpy as np
arr = np.arange(int(input()))
print("1D Array :")
print(arr)
print(arr.shape)
print("2D Arrays :")
arr1=arr[ np.newaxis]
print("For ROW :",arr1)
print(arr1.shape)
arr2=arr[:,np.newaxis]
print("For Column : ",arr2)
print(arr2.shape)


4
1D Array :
[0 1 2 3]
(4,)
2D Arrays :
For ROW : [[0 1 2 3]]
(1, 4)
For Column :  [[0]
 [1]
 [2]
 [3]]
(4, 1)


In [5]:
#Question NO. 5

import numpy as np

arr1= np.square([1, 4, 5, 8,11])
arr2= np.square([4, 5, 8, 6, 9])
print(arr1)


print(" horizontally stacked :", np.hstack((arr1,arr2)))

print("vertically stacked : ", np.vstack((arr1,arr2)))



[  1  16  25  64 121]
 horizontally stacked : [  1  16  25  64 121  16  25  64  36  81]
vertically stacked :  [[  1  16  25  64 121]
 [ 16  25  64  36  81]]


In [6]:
#Question NO. 6

import numpy
arr= numpy.array([1, 1, 2,2, 3, 4, 4, 1])
print(arr)
uni= numpy.unique(arr)
print("Unique values : ",uni)
print("Count of Unique Values :",len(uni))

[1 1 2 2 3 4 4 1]
Unique values :  [1 2 3 4]
Count of Unique Values : 4
